### PR TITLE
use absolute paths for cadence scripts

### PR DESCRIPTION
**Pull request by colinschmidt**
It seems like cadence tools don't like non-absolute paths or its just in the wrong place, either way this seems like a good solution.

### CODE REVIEW

**Comment by colinschmidt** [comment]
There are a couple more of these coming so wait a bit to merge.

**Comment by edwardcwang** [comment]
Thanks for alerting me to this - so it turns out that there is actually a bug in the cli_driver that causes obj_dir to be blank since it tries to get hammer_vlsi_path before it's ready. I'll push a PR.

**Comment by edwardcwang** [comment]
#62

**Comment by edwardcwang** [comment]
Closed via #62

**Pull request closed without merging**
