### PR TITLE
asap7 (take 2)

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by sequencer** [comment]
Just added some default mmmc settings.
And working on the lvs/drc tool.

**Comment by sequencer** [comment]
I have a question that, files `asap7_75t_SL.cdl` and `asap7_75t_SRAM.cdl` in `/tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7libs_24.tar.bz2/asap7libs_24/cdl/lvs` seem to be a same file:
```
diff asap7_75t_SL.cdl asap7_75t_SRAM.cdl
4c4
< * Library Name:  asap7sc7p5t_23_SL
---
> * Library Name:  asap7sc7p5t_24_SRAM
24c24
< * Library Name: asap7sc7p5t_23_SL
---
> * Library Name: asap7sc7p5t_24_SRAM
```
Is this normal? I thought it was a bug from asap7

**Comment by sequencer** [comment]
> I have a question that, files `asap7_75t_SL.cdl` and `asap7_75t_SRAM.cdl` in `/tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7libs_24.tar.bz2/asap7libs_24/cdl/lvs` seem to be a same file:
> 
> ```
> diff asap7_75t_SL.cdl asap7_75t_SRAM.cdl
> 4c4
> < * Library Name:  asap7sc7p5t_23_SL
> ---
> > * Library Name:  asap7sc7p5t_24_SRAM
> 24c24
> < * Library Name: asap7sc7p5t_23_SL
> ---
> > * Library Name: asap7sc7p5t_24_SRAM
> ```
> 
> Is this normal? I thought it was a bug from asap7

I just emailed Vinay Vashishtha, author of asap7, hope this can be fixed later.

**Comment by sequencer** [comment]
lvs by calibre still remains bug
```
Error:    Nothing in layout.
```
This may need additional tuning :(

**Comment by sequencer** [comment]
> > I have a question that, files `asap7_75t_SL.cdl` and `asap7_75t_SRAM.cdl` in `/tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7libs_24.tar.bz2/asap7libs_24/cdl/lvs` seem to be a same file:
> > ```
> > diff asap7_75t_SL.cdl asap7_75t_SRAM.cdl
> > 4c4
> > < * Library Name:  asap7sc7p5t_23_SL
> > ---
> > > * Library Name:  asap7sc7p5t_24_SRAM
> > 24c24
> > < * Library Name: asap7sc7p5t_23_SL
> > ---
> > > * Library Name: asap7sc7p5t_24_SRAM
> > ```
> > 
> > 
> > Is this normal? I thought it was a bug from asap7
> 
> I just emailed Vinay Vashishtha, author of asap7, hope this can be fixed later.

I have reached asap7 author for this bug. This will be fixed in next release.

**Comment by harrisonliew** [comment]
@sequencer I'm currently trying to update #447 so that we can specify the rule deck from the tarball when using the mentor plugin. When using Calibre, did you also run into errors with the rule deck (undefined variable) and missing Vt (due to GDS)?

**Comment by sequencer** [comment]
I'm debugging LVS currently, extracting layers from gds returns nothing.
DRC has similar issues.
So maybe in my side, the rule deck is still not being used, since the error
```
ERROR: Nothing in layout.
``` 
BTW, I'm using `ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7PDK_r1p5.tar.bz2/asap7PDK_r1p5/calibre/ruledirs/drc/drcRules_calibre_asap7_171111a.rul` as the drc rule.

**Comment by harrisonliew** [comment]
Hmm, perhaps you may not have done the GDS writing correctly from P&R? (Regarding the GDS issue I emailed the ASAP7 dev, Vinay also).

I think I'm a bit farther than you in the debugging of DRC/LVS. I am using both supplied rule decks, but I have the following errors:

For LVS:
`ERROR: Rule file precision 4000 is not consistent with database precision 1000 in input file <my design's GDS file>.`

For DRC:
`ERROR: Error ENV1 on line 841 of /tools/B/harrisonliew/chipyard/vlsi/build/tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7PDK_r1p5.tar.bz2/asap7PDK_r1p5/calibre/ruledirs/drc/drcRules_calibre_asap7.rul - undefined or empty environment variable: VAR_M4_YOFFSET.`

**Comment by sequencer** [comment]
I generate the PaR directly by hammer script.
```
hammer-vlsi synthesis -o syn-output.json
hammer-vlsi synthesis_to_par -p syn-output.json -o par-run.json
hammer-vlsi par -p par-run.json -o par-output.json
hammer-vlsi par_to_lvs -p par-output.json -o lvs-run.json
hammer-vlsi lvs -p lvs-run.json -o lvs-output.json
```
using klayout can view the layout.
I'm still figuring out what the problem is:(

**Comment by sequencer** [comment]
> VAR_M4_YOFFSET

I notice this env is located at 
`tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7PDK_r1p5.tar.bz2/asap7PDK_r1p5/cdslib/setup/set_pdk_path.csh`
we might need to add some env from the `set_pdk_path.csh` to solve your problem.

**Comment by sequencer** [comment]
`tech-asap7-cache/extracted/ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7PDK_r1p5.tar.bz2/asap7PDK_r1p5/README_ASAP7PDK_INSTALL_171112a.txt
` says we should set env lib path by source `./cdslib/setup/set_pdk_path.csh` 
However from `set_pdk_path.csh`, it also set some `grids offsets` and caused your issue. 
```
# These environmental variables specify the metal grids offsets from either
# X or Y axis, depending on the metal routing direction. The default offset
# value is 0 nm. To offset a particular grid by 'p' nm, specify the
# variable value as p*10.  Thus, for an offset of 24 nm, the corresponding
# variable value is 240.

setenv VAR_M4_YOFFSET "0"
setenv VAR_M5_XOFFSET "0"
setenv VAR_M6_YOFFSET "0"
setenv VAR_M7_XOFFSET "0"
```

**Comment by harrisonliew** [comment]
I see, I did not source `set_pdk_path.csh` so the error makes sense.

I figured out how to do this in Hammer. The following lines need to be added to the `defaults.yml` in this PR:

```
mentor.extra_env_vars:
  - VAR_M4_YOFFSET: "0"
  - VAR_M5_XOFFSET: "0"
  - VAR_M6_YOFFSET: "0"
  - VAR_M7_XOFFSET: "0"
```

**Comment by harrisonliew** [comment]
Thanks for adding it!

Next problem with Calibre is that specification statements cannot be duplicated according to the SVRF manual (error says `superfluous specification statement`). The default DRC rules file has a set of specification statements at the top which should be user set (e.g. the path to the GDS file), not in the rules file.

I will work on trying to remove these from the rules file.

**Comment by harrisonliew** [comment]
Did you run into an issue where by taking out all of the "SRAM" libraries, Innovus was unable to find available clock tree inverters and buffers? The "INVBUF..." libs are read properly by Innovus but it seemingly cannot determine that all of the Vt flavors can be used for clock inverters/buffers/clock gates.

I'll ask Vinay; it appears they did not do any special setting of clock tree cells in their example Innovus script.

**Comment by sequencer** [comment]
> Vinay recommends that we should re-enable the SRAM library, and edit the CDLs to change the cell name and transistor name suffixes

But we still didn't have SRAM cell accurate data? Is this reasonable? will SRAM cell a little odd in the general design? 

I'm still stuck at the lvs/drc :(
```
Identifying CORRESPONDING cells ...
      ERROR:  Nothing in layout.
``` 
Have no idea in this problem :(

**Comment by harrisonliew** [comment]
I am beginning to believe that the "SRAM" in this PDK is just a version of all the same cells but instead abides by SRAM DRC rules, which are tighter than regular DRC rules. I can't identify any actual SRAM bit cells in the libraries.

Did you take out the `LAYOUT PRIMARY TOPCELL` from the default rule decks and replace it with your own? I found that the following keys need to be removed from the DRC/LVS rule files so that they are not duplicated from the hammer-mentor-plugin:
`LAYOUT PATH`
`LAYOUT PRIMARY`
`LAYOUT SYSTEM`
`DRC RESULTS DATABASE`
`DRC SUMMARY REPORT`
`LVS REPORT`
`LVS POWER NAME`
`LVS GROUND NAME`

**Comment by sequencer** [comment]
> I am beginning to believe that the "SRAM" in this PDK is just a version of all the same cells but instead abides by SRAM DRC rules, which are tighter than regular DRC rules. I can't identify any actual SRAM bit cells in the libraries.

Got it. So we just need to `sed` all `SL` to `SRAM` then can fix this issue? It there any method to implement post-install script for a tech library to do patch things like this?
 
> Did you take out the LAYOUT PRIMARY TOPCELL from the default rule decks and replace it with your own? I found that the following keys need to be removed from the DRC/LVS rule files so that they are not duplicated from the hammer-mentor-plugin:

I'll try with current version, my tutor is out to Shenzhen this week, and next week I'll in Beijing, I'll prompt him after I come back for the NDA issue.

**Comment by harrisonliew** [comment]
> Got it. So we just need to sed all SL to SRAM then can fix this issue? It there any method to implement post-install script for a tech library to do patch things like this?

I'm currently working in the `asap7_drc_lvs` branch, and I committed a `setup.sh` script to be run on the extracted tarball dir to hotfix the PDK. I used the `python-gdsii` package to manipulate the GDS. I still need to write the code to specify and source this script after extracting the tarball the first time (#506).

I did not PR anything yet, so that you can have an idea of what things I needed to change.

My status is that both DRC & LVS rule decks now load properly with my design, but DRC appears to hang and my LVS test case is now only missing a SPICE netlist for a hard macro.

**Comment by harrisonliew** [comment]
@sequencer I successfully got through DRC & LVS, but they are not clean. According to the developers, it seems like they released it without having a fully DRC clean (post-P&R deck) and they never tried post-P&R LVS, so I'm not sure how much cleaner I can get my test case without modifying actual rules.

Would you mind if I just started a different PR from the `asap7_drc_lvs` branch that includes most of your changes in here?

**Comment by sequencer** [comment]
Sure! I'll rebase to your PR after yours is merged.
I got food poison the day before yesterday, sorry not so much available contributions:(
I'll settle down tomorrow and work on the post/pre hook for automatically hacking vendor libraries.

**Comment by harrisonliew** [comment]
Sure thing, hope you get well soon! The hacking of vendor libraries will be included in that PR.

**Pull request closed without merging**
