### PR TITLE
Don't add empty configs if given empty strings

### PR DESCRIPTION
**Pull request by colinschmidt**
In addition to ignoring null lists also ignore empty strings in a list

### CODE REVIEW

**Comment by edwardcwang** [comment]
Is the goal for hammer to ignore the empty string in  `hammer-vlsi ... -p my_snippet.json -p "" -p foo.json`? Or is there another way in which the empty string sneaks in?

**Comment by colinschmidt** [comment]
If I don't set the environment variable then it puts a blank string in see https://github.com/ucb-bar/hammer/blob/master/src/hammer-vlsi/cli_driver.py#L74

**Comment by colinschmidt** [comment]
I didn't want to mess up that one-liner since I didn't know enough python to make it look good. open to other suggestions

**Comment by edwardcwang** [comment]
Since we want to prevent an unset environment variable from injecting a blank config but also want to catch `-p ""`, this seems like it will work.

**Pull request merged**
