### PR TITLE
Add top_layer/pg_pins_layers/stripe_pins flags to write_ilm for hierarchical flows

### PR DESCRIPTION
**Pull request by jerryz123**
**Related PRs / Issues**

**Type of change**:
- [ ] Bug fix
- [x] New feature
- [ ] Other enhancement

**Impact**:
- [x] Change to core Hammer
- [ ] Change to a Hammer plugin
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `master` as the base branch?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you update the `poetry.lock` file if you updated the requirements in `pyproject.toml`?
- [ ] (If applicable) Did you add a unit test demonstrating the PR?
- [ ] (If applicable) Did you run this through the e2e integration tests?
- [ ] (If applicable) Did you update the submodules in `e2e/` if this feature depends on updated plugins?

### CODE REVIEW

**Comment by harrisonliew** [comment]
Hm, can't we just set the stripe pins and top layer arguments based on the power straps pin_layer field?

**Comment by jerryz123** [comment]
Is that general enough though for all use cases? For instance, If you have a power island in a block that instantiates its own bump, what would the flags to this command need to be?

I figured there will frequently be cases where you'll need some specialized settings to achieve what you want.

**Comment by harrisonliew** [comment]
In the user guide:

In a bottom-up flow (where the block was not created using the create_partition command), you normally create a simple LEF abstract that contains:
- one obstruction (OBS) shape per routing layer
- signal pins located along the block boundary
- add power pins for the top metal layer PG stripes (see –stripe_pins and –pg_pin_layers options)
- embedded bump pins shapes are also written out as LEF pin shapes

So, it seems like `-stripe_pins` and `-pg_pin_layers` is sufficient. If you want more options, that's what a replacement hook is for. Otherwise adding all these keys for command options gets unwieldy.

**Comment by jerryz123** [comment]
Ok, I'll change this then.

**Comment by jerryz123** [comment]
Should we at least handle the case where manual power straps are used, in which case the `by_tracks.pin_layers` option is unset?

**Comment by harrisonliew** [comment]
No, I think if you're doing manual straps, you're already using hooks and being mindful of stripe pin layers. At most, add an additional comment for the `by_tracks.pin_layers` key to note that this is used when writing out LEF/DEF of the layout (user can always set this key even if they're using manual straps).

**Comment by jerryz123** [comment]
> No, I think if you're doing manual straps, you're already using hooks and being mindful of stripe pin layers. At most, add an additional comment for the `by_tracks.pin_layers` key to note that this is used when writing out LEF/DEF of the layout (user can always set this key even if they're using manual straps).

**Review by harrisonliew — APPROVED** [review]

**Pull request merged**
