### PR TITLE
Add a hierarchical constraint field that overrides generic constraint…

### LINKED ISSUE #127: Add vlsi.inputs.hierarchical.custom_config array
Useful for hierarchical to specify custom configs for each layer in the hierarchy

@colinschmidt

### PR DESCRIPTION
**Pull request by colinschmidt**
…s per module

Fixes #127

### CODE REVIEW

**Comment by colinschmidt** [comment]
That was way easier than expected.

**Comment by edwardcwang** [comment]
Might be good to have a unit test.

**Comment by colinschmidt** [comment]
@edwardcwang I've added a unit test.

**Comment by edwardcwang** [comment]
Will take a look

**Pull request merged**
