### PR TITLE
Add alpha web interface

### PR DESCRIPTION
**Pull request by edwardcwang**
Still in alpha development

### CODE REVIEW

**Comment by ben-k** [comment]
Should this be reviewed or is more work needed?

**Comment by edwardcwang** [comment]
I think it's OK for preliminary review. The web interface is only really FPGA (vivado) tested for now.

**Comment by edwardcwang** [comment]
@ben-k Would you like to give it a quick review?

**Comment by ben-k** [comment]
I don't know enough about this to review it at this point.

**Comment by edwardcwang** [comment]
Punting to #316

**Pull request closed without merging**
