### PR TITLE
add asap7 support

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by sequencer** [comment]
recreate https://github.com/ucb-bar/hammer/pull/443, and be able to synthesis with genus.
https://github.com/ucb-bar/hammer/pull/445 is also needed, because original tar is nested.

**Comment by sequencer** [comment]
> I don't think ASAP7 should be the default. In fact, I think the current default is also wrong- it should be `nop`, IMO.

Done.

**Comment by sequencer** [comment]
any updates?

**Comment by edwardcwang** [comment]
Hey @sequencer - to follow up, the plan for this PR specifically is to review/test/merge #445 and then we will review/test this PR and get it in.

**Comment by sequencer** [comment]
OK, thx!!

**Pull request merged**
