### PR TITLE
SAED32 redundant vias fix

### PR DESCRIPTION
**Pull request by edwardcwang**

### CODE REVIEW

**Comment by colinschmidt** [comment]
Is this the only technology specific code in PLSI? You should probably at least ifdef it no?

**Comment by edwardcwang** [comment]
Eventually it'll be refactored into the technology files themselves I think once we've figured out how exactly to make this work, but for now I think a TODO should suffice since time of the essence.

**Comment by colinschmidt** [comment]
Not to be a jerk but these TODO's are why cad tool scripts are hard to use.
Would you mind ifdefing it out so this doesn't fail for some other technology needlessly?

**Comment by edwardcwang** [comment]
After some further discussion, I think there is a way to do this more generically. I will do that instead with a more generic solution.

**Comment by edwardcwang** [comment]
Closing this as refactor is about to happen anyway, and we will use the new config system avoid issues like this.

**Pull request closed without merging**
