### PR TITLE
remove saed32

### PR DESCRIPTION
**Pull request by sequencer**
based on the #503,
after lvs/drc for asap7 success, this could be merged.

### CODE REVIEW

**Comment by jwright6323** [comment]
LGTM, @harrisonliew can you review?

**Comment by harrisonliew** [comment]
LGTM too, thanks @sequencer!

**Comment by farzadfch** [comment]
I am new to hammer and I was considering using saed32. I wonder why saed32 is removed. Is there something particularly wrong about saed32 or it's just the matter of giving up on supporting it in hammer?

**Comment by jwright6323** [comment]
SAED32 is proprietary intellectual property of Synopsys, and we can't support it publicly, so we are opting to use ASAP7 instead, as it has a less restrictive EULA.

**Pull request merged**
