### PR TITLE
Use line buffering in popen

### LINKED ISSUE #64: Output from tools being buffered too long
Unclear if this is a hammer or outer build system problem (lsf) but it certainly is annoying, and running tools manually in lsf does not present this issue.

### PR DESCRIPTION
**Pull request by colinschmidt**
This makes it easier to tail hammer's output if using lsf or something else.
Some cad commands take a long time and so not knowing exactly which line hammer is on can be confusing.

Also this linebreak at the end keeps coming up in my diffs so maybe our editors are fighting, and we'll see if mine wins ;)

Closes #64

### CODE REVIEW

**Comment by edwardcwang** [comment]
According to https://docs.python.org/3/library/subprocess.html#popen-constructor

```1 means line buffered (only usable if universal_newlines=True i.e., in a text mode)```

Do we need to set `universal_newlines=True` as well?

**Comment by colinschmidt** [comment]
Experimentally it worked for me, so either its true by default or this is `a text mode` which seems likely.

**Comment by colinschmidt** [comment]
Hmm it does seem not to be set by default. Do you want me to also set that?

**Comment by edwardcwang** [comment]
If you can briefly check that `universal_newlines=True` doesn't cause any harm I think we may as well set it.

**Comment by colinschmidt** [comment]
Still testing. Don't merge

**Comment by colinschmidt** [comment]
I don't think so. closing until further notice

**Pull request closed without merging**
