### PR TITLE
Indentation helper switch

### PR DESCRIPTION
**Pull request by jwright6323**
Add an option to allow user to use hammer_tool.*append with nice python indentation and remove it in the output code.

### CODE REVIEW

**Comment by jwright6323** [comment]
@edwardcwang @colinschmidt I plan on using this for the upcoming favorite_technology_plugin_hook stuff, so it'd be nice to get this in quickly despite it being fairly unimportant.

**Comment by colinschmidt** [comment]
To clarify this makes things like
```
tool.verbose_append("""
  2 space indent
    4 space indent
  2 space indent
""")
```
to be printed as
```
2 space indent
  4 space indent
2 space indent
```

**Comment by jwright6323** [comment]
Yes, correct.

**Comment by edwardcwang** [comment]
@jwright6323 Can we add Colin's example to the pydoc? I feel that it makes the flag much easier to understand when new to it.

**Comment by jwright6323** [comment]
I'm not sure how you'd do that cleanly in the pydoc without also running into indentation issues, but if you'd like to add it be my guest.

**Pull request merged**
