### PR TITLE
Remove unnecessary timing conditions

### PR DESCRIPTION
**Pull request by Rholais**
`create_timing_condition` is invalid in the later version of Innovus.

### CODE REVIEW

**Comment by edwardcwang** [comment]
Hello, thank you for your PR. Starting from what Innovus version is create_timing_condition invalid?

**Comment by Rholais** [comment]
> Hello, thank you for your PR. Starting from what Innovus version is create_timing_condition invalid?

I didn't find this command in Innovus 18.1.

**Comment by edwardcwang** [comment]
I see. Are you launching Innovus with Common UI? We only support Common UI TCL (vs. legacy TCL).

**Comment by Rholais** [comment]
> I see. Are you launching Innovus with Common UI? We only support Common UI TCL (vs. legacy TCL).

Thank you for the information!
It resolved my problem and I will close the pull request.

**Pull request closed without merging**
