### PR TITLE
Add power specification support

### PR DESCRIPTION
**Pull request by colinschmidt**
Not tested yet but wanted to see if anyone had early feedback

### CODE REVIEW

**Comment by edwardcwang** [comment]
Are we interested in an `auto` mode and corresponding higher-level API to generate the power spec automatically?

**Comment by colinschmidt** [comment]
Yes we do want that. It won't be in this PR but I can add the mode setting and mark it not implemented if you would prefer.

**Comment by edwardcwang** [comment]
Yes, how about let's add an `auto` mode and mark it as unimplemented for now. e.g. `raise NotImplementedError("...")`

**Comment by colinschmidt** [comment]
Rebased and fixed feedback

**Comment by edwardcwang** [comment]
Generally looks good. What do you think about `power_spec_path` -> `power_spec_contents`? This will make things a bit easier and more deterministic for programs that generate Hammer IR (i.e. not having to worry about finding a temporary folder and dumping the file). It also gives more options for specifying the location of the file (e.g. we could do a subst to get the filename then transclude to get the contents).

```
vlsi.inputs:
  power_spec_contents: "mychip.cpf"
  power_spec_contents_meta: transclude
```

**Comment by colinschmidt** [comment]
Hmm. That means hammer will have to write the contents to a file, and this will be a very long string. I think your suggestion does mirror what happened with floorplan constraints though. And I can see the evolution of power specifications following that path as well. Initially just raw power specification constraints as a dump in Hammer, then IR updates that let you specify similar constraints as hammerIR and then either a DSL or higher level IR constraints.

I'll make the updates soon. Thanks for the feedback.

**Comment by colinschmidt** [comment]
Fixed. Tested on a demo.

**Pull request merged**
